import {
    VerticalBox,
    HorizontalBox,
    LineEdit,
    Button,
    Palette
} from "std-widgets.slint";
import { DirectoryList, FileEntry } from "dir-list.slint";
import { Notification } from "notification.slint";

export component AppWindow inherits Window {
    in property <[FileEntry]> files;
    in property <string> search-path;
    callback directory_changed(string);
    callback show_notification(string);
    callback entry_clicked(int);
    callback go_back();
    callback go_forward();
    callback go_up();

    show_notification(message) => {
        notification.show(message);
    }

    // Styling props  //
    min-width: 400px;
    min-height: 240px;
    preferred-width: 640px;
    preferred-height: 480px;
    // ============== //

    title: "File Manager";

    Rectangle {
        VerticalBox {
            padding: 8px;

            HorizontalLayout {
                spacing: 5px;

                Button {
                    icon: @image-url("../icons/caret-left-fill.svg");
                    colorize-icon: true;
                    clicked => {
                        go_back();
                    }
                }

                Button {
                    icon: @image-url("../icons/caret-right-fill.svg");
                    colorize-icon: true;
                    clicked => {
                        go_forward();
                    }
                }

                Button {
                    icon: @image-url("../icons/caret-up-fill.svg");
                    colorize-icon: true;
                    clicked => {
                        go_up();
                    }
                }

                LineEdit {
                    placeholder-text: "Enter directory path...";
                    text: search-path;

                    accepted(text) => {
                        directory_changed(text);
                    }
                }
            }

            DirectoryList {
                files: files;
                entry_clicked(entry) => {
                    root.entry_clicked(entry);
                }
            }
        }

        notification := Notification {
            x: parent.width - self.width - 25px;
            y: parent.height - self.height - 25px;
        }
    }
}
