import {
    VerticalBox,
    HorizontalBox,
    ListView,
} from "std-widgets.slint";

export struct FileEntry { id: int, name: string, is_directory: bool }

export component DirectoryListElement inherits Rectangle {
    in property <FileEntry> file;
    callback clicked;

    background: touch.has-hover ? #50a3e2a8 : transparent;

    touch := TouchArea {
        clicked => {
            root.clicked();
        }

        HorizontalLayout {
            height: 32px;
            cross-axis-alignment: center;

            Text {
                text: file.is_directory ? "📁" : "📄";
                width: 30px;
                font-size: 20px;
            }

            Text {
                text: file.name;
                font-size: 20px;
            }
        }
    }
}

export component DirectoryList inherits VerticalBox {
    in property <[FileEntry]> files;
    callback entry_clicked(int);

    padding: 10px;

    Rectangle {
        border-color: gainsboro;
        border-width: 2px;
        border-radius: 12px;
        background: whitesmoke;

        VerticalLayout {
            padding: 8px;

            ListView {
                for file[index] in files: DirectoryListElement {
                    file: file;
                    clicked => {
                        entry_clicked(index);
                    }
                }
            }
        }
    }
}
