import { Palette } from "std-widgets.slint";

export struct TabInfo { title: string, active: bool }

export component TabBar inherits Rectangle {
    in property <[TabInfo]> tabs;

    callback tab_clicked(int);
    callback new_tab();
    callback close_tab(int);

    background: Palette.alternate-background;

    HorizontalLayout {
        spacing: 2px;

        for tab[idx] in tabs: Rectangle {
            height: 36px;

            background: tab.active
                ? Palette.background
                : Palette.alternate-background;

            border-color: tab.active
                ? Palette.border
                : transparent;

            border-width: 1px;
            border-radius: 6px;

            HorizontalLayout {
                padding-left: 12px;
                padding-right: 8px;
                spacing: 8px;

                TouchArea {
                    clicked => {
                        tab_clicked(idx);
                    }

                    Text {
                        text: tab.title;
                        vertical-alignment: center;
                    }
                }

                TouchArea {
                    width: 20px;

                    clicked => {
                        close_tab(idx);
                    }

                    Text {
                        text: "×";
                        font-size: 18px;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                }
            }
        }

        TouchArea {
            width: 36px;
            clicked => {
                new_tab();
            }

            Text {
                text: "+";
                font-size: 22px;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }

        Rectangle {
            horizontal-stretch: 1;
        }
    }
}